### ISSUE TITLE
make build报错

### ISSUE THREAD

**Issue by whistlesun** [z-2x/cinema#2]
172:cinema sun$ make build
./build.sh
building... /Users/sun/Go/src/cinema/user
handler/user.go:10:2: cannot find package "github.com/getsentry/raven-go" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/getsentry/raven-go (from $GOROOT)
	/Users/sun/Go/src/github.com/getsentry/raven-go (from $GOPATH)
main.go:8:2: cannot find package "github.com/micro/go-log" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-log (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-log (from $GOPATH)
main.go:9:2: cannot find package "github.com/micro/go-micro" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro (from $GOPATH)
handler/user.go:11:2: cannot find package "github.com/micro/go-micro/broker" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/broker (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/broker (from $GOPATH)
pb/user/user.micro.go:25:2: cannot find package "github.com/micro/go-micro/client" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/client (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/client (from $GOPATH)
main.go:11:2: cannot find package "github.com/micro/go-micro/cmd" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/cmd (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/cmd (from $GOPATH)
pb/user/user.micro.go:26:2: cannot find package "github.com/micro/go-micro/server" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/server (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/server (from $GOPATH)
plugin.go:4:2: cannot find package "github.com/micro/go-plugins/broker/kafka" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-plugins/broker/kafka (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-plugins/broker/kafka (from $GOPATH)
handler/user.go:12:2: cannot find package "github.com/mongodb/mongo-go-driver/bson" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/bson (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/bson (from $GOPATH)
handler/user.go:13:2: cannot find package "github.com/mongodb/mongo-go-driver/bson/primitive" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/bson/primitive (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/bson/primitive (from $GOPATH)
module/mongo.go:5:2: cannot find package "github.com/mongodb/mongo-go-driver/mongo" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/mongo (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/mongo (from $GOPATH)
handler/user.go:14:2: cannot find package "github.com/mongodb/mongo-go-driver/x/bsonx" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/x/bsonx (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/x/bsonx (from $GOPATH)
building... /Users/sun/Go/src/cinema/api
caech/redis.go:4:2: cannot find package "github.com/go-redis/redis" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/go-redis/redis (from $GOROOT)
	/Users/sun/Go/src/github.com/go-redis/redis (from $GOPATH)
proto/user/user.micro.go:25:2: cannot find package "github.com/micro/go-micro/client" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/client (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/client (from $GOPATH)
proto/user/user.micro.go:26:2: cannot find package "github.com/micro/go-micro/server" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/server (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/server (from $GOPATH)
main.go:5:2: cannot find package "github.com/micro/go-web" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-web (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-web (from $GOPATH)
building... /Users/sun/Go/src/cinema/movie
main.go:4:2: cannot find package "github.com/micro/go-log" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-log (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-log (from $GOPATH)
main.go:5:2: cannot find package "github.com/micro/go-micro" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro (from $GOPATH)
main.go:6:2: cannot find package "github.com/micro/go-micro/broker" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/broker (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/broker (from $GOPATH)
main.go:7:2: cannot find package "github.com/micro/go-micro/cmd" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro/cmd (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro/cmd (from $GOPATH)
plugin.go:4:2: cannot find package "github.com/micro/go-plugins/broker/kafka" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-plugins/broker/kafka (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-plugins/broker/kafka (from $GOPATH)
building... /Users/sun/Go/src/cinema/projection
main.go:5:2: cannot find package "github.com/micro/go-log" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-log (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-log (from $GOPATH)
main.go:6:2: cannot find package "github.com/micro/go-micro" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/micro/go-micro (from $GOROOT)
	/Users/sun/Go/src/github.com/micro/go-micro (from $GOPATH)
module/projectionRoom.go:6:2: cannot find package "github.com/mongodb/mongo-go-driver/bson" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/bson (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/bson (from $GOPATH)
module/projectionRoom.go:7:2: cannot find package "github.com/mongodb/mongo-go-driver/bson/primitive" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/bson/primitive (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/bson/primitive (from $GOPATH)
module/module.go:5:2: cannot find package "github.com/mongodb/mongo-go-driver/mongo" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/mongo (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/mongo (from $GOPATH)
module/projectionRoom.go:8:2: cannot find package "github.com/mongodb/mongo-go-driver/x/bsonx" in any of:
	/usr/local/Cellar/go/1.12.1/libexec/src/github.com/mongodb/mongo-go-driver/x/bsonx (from $GOROOT)
	/Users/sun/Go/src/github.com/mongodb/mongo-go-driver/x/bsonx (from $GOPATH)

**Comment by z-2x** [comment]
没找到依赖包你可以执行如下操作：
```shell
# 设置go下载代理
export GOPROXY=https://goproxy.io
# 开启go mod
export GO111MODULE=on
# 整理包
go mod tidy
# build
make build
```
